### ISSUE TITLE
NVIC_PRIO_BITS from PAC?

### ISSUE THREAD

**Issue by nickray** [japaric/cortex-m-funnel#1]
Hey this library is amazing, just what I needed, thanks a lot!

I put together an RTFM example (https://git.sr.ht/~nickray/lpc55-examples/tree/master/logging/src/main_rtfm.rs) but would like to pass the NVIC_PRIO_BITS from the device PAC. It seems your macro expects a literal integer? Apologies for not providing a patch, proc-macros are on my learn-soon-but-not-right-now list :/

**Comment by japaric** [comment]
Yes, it's possible to support paths and literal integers. The downside of paths is that you'll get confusing compile time error messages ("attempt to subtract with overflow") when you pass a bad priority. Example:

``` rust
// let's say the device has 3 priority bits
funnel!(NVIC_PRIO_BITS = device::NVIC_PRIO_BITS, { //~ ERROR: attempt to subtract with overflow
    6: 32, // OK
    9: 32, // bad
});
```

**Comment by nickray** [comment]
Ooh, `Either` is nice. Thanks!
